source 'https://github.com/CocoaPods/Specs.git'
# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'rivi-candidate-rater-ios' do
	pod 'Alamofire', '3.2.1'
    pod 'AlamofireImage', '~> 2.0'
    pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
end

target 'rivi-candidate-rater-iosTests' do

end

target 'rivi-candidate-rater-iosUITests' do

end

